// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Vadd_A_B,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu200-fsgd2104-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=24609,HLS_SYN_TPT=none,HLS_SYN_MEM=64,HLS_SYN_DSP=0,HLS_SYN_FF=1705,HLS_SYN_LUT=2245,HLS_VERSION=2019_1}" *)

module Vadd_A_B (
        ap_clk,
        ap_rst_n,
        m_axi_m00_axi_AWVALID,
        m_axi_m00_axi_AWREADY,
        m_axi_m00_axi_AWADDR,
        m_axi_m00_axi_AWID,
        m_axi_m00_axi_AWLEN,
        m_axi_m00_axi_AWSIZE,
        m_axi_m00_axi_AWBURST,
        m_axi_m00_axi_AWLOCK,
        m_axi_m00_axi_AWCACHE,
        m_axi_m00_axi_AWPROT,
        m_axi_m00_axi_AWQOS,
        m_axi_m00_axi_AWREGION,
        m_axi_m00_axi_AWUSER,
        m_axi_m00_axi_WVALID,
        m_axi_m00_axi_WREADY,
        m_axi_m00_axi_WDATA,
        m_axi_m00_axi_WSTRB,
        m_axi_m00_axi_WLAST,
        m_axi_m00_axi_WID,
        m_axi_m00_axi_WUSER,
        m_axi_m00_axi_ARVALID,
        m_axi_m00_axi_ARREADY,
        m_axi_m00_axi_ARADDR,
        m_axi_m00_axi_ARID,
        m_axi_m00_axi_ARLEN,
        m_axi_m00_axi_ARSIZE,
        m_axi_m00_axi_ARBURST,
        m_axi_m00_axi_ARLOCK,
        m_axi_m00_axi_ARCACHE,
        m_axi_m00_axi_ARPROT,
        m_axi_m00_axi_ARQOS,
        m_axi_m00_axi_ARREGION,
        m_axi_m00_axi_ARUSER,
        m_axi_m00_axi_RVALID,
        m_axi_m00_axi_RREADY,
        m_axi_m00_axi_RDATA,
        m_axi_m00_axi_RLAST,
        m_axi_m00_axi_RID,
        m_axi_m00_axi_RUSER,
        m_axi_m00_axi_RRESP,
        m_axi_m00_axi_BVALID,
        m_axi_m00_axi_BREADY,
        m_axi_m00_axi_BRESP,
        m_axi_m00_axi_BID,
        m_axi_m00_axi_BUSER,
        m_axi_m01_axi_AWVALID,
        m_axi_m01_axi_AWREADY,
        m_axi_m01_axi_AWADDR,
        m_axi_m01_axi_AWID,
        m_axi_m01_axi_AWLEN,
        m_axi_m01_axi_AWSIZE,
        m_axi_m01_axi_AWBURST,
        m_axi_m01_axi_AWLOCK,
        m_axi_m01_axi_AWCACHE,
        m_axi_m01_axi_AWPROT,
        m_axi_m01_axi_AWQOS,
        m_axi_m01_axi_AWREGION,
        m_axi_m01_axi_AWUSER,
        m_axi_m01_axi_WVALID,
        m_axi_m01_axi_WREADY,
        m_axi_m01_axi_WDATA,
        m_axi_m01_axi_WSTRB,
        m_axi_m01_axi_WLAST,
        m_axi_m01_axi_WID,
        m_axi_m01_axi_WUSER,
        m_axi_m01_axi_ARVALID,
        m_axi_m01_axi_ARREADY,
        m_axi_m01_axi_ARADDR,
        m_axi_m01_axi_ARID,
        m_axi_m01_axi_ARLEN,
        m_axi_m01_axi_ARSIZE,
        m_axi_m01_axi_ARBURST,
        m_axi_m01_axi_ARLOCK,
        m_axi_m01_axi_ARCACHE,
        m_axi_m01_axi_ARPROT,
        m_axi_m01_axi_ARQOS,
        m_axi_m01_axi_ARREGION,
        m_axi_m01_axi_ARUSER,
        m_axi_m01_axi_RVALID,
        m_axi_m01_axi_RREADY,
        m_axi_m01_axi_RDATA,
        m_axi_m01_axi_RLAST,
        m_axi_m01_axi_RID,
        m_axi_m01_axi_RUSER,
        m_axi_m01_axi_RRESP,
        m_axi_m01_axi_BVALID,
        m_axi_m01_axi_BREADY,
        m_axi_m01_axi_BRESP,
        m_axi_m01_axi_BID,
        m_axi_m01_axi_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 30'd1;
parameter    ap_ST_fsm_state2 = 30'd2;
parameter    ap_ST_fsm_state3 = 30'd4;
parameter    ap_ST_fsm_state4 = 30'd8;
parameter    ap_ST_fsm_state5 = 30'd16;
parameter    ap_ST_fsm_state6 = 30'd32;
parameter    ap_ST_fsm_state7 = 30'd64;
parameter    ap_ST_fsm_state8 = 30'd128;
parameter    ap_ST_fsm_pp0_stage0 = 30'd256;
parameter    ap_ST_fsm_state12 = 30'd512;
parameter    ap_ST_fsm_pp1_stage0 = 30'd1024;
parameter    ap_ST_fsm_state15 = 30'd2048;
parameter    ap_ST_fsm_pp2_stage0 = 30'd4096;
parameter    ap_ST_fsm_state19 = 30'd8192;
parameter    ap_ST_fsm_state20 = 30'd16384;
parameter    ap_ST_fsm_state21 = 30'd32768;
parameter    ap_ST_fsm_state22 = 30'd65536;
parameter    ap_ST_fsm_state23 = 30'd131072;
parameter    ap_ST_fsm_state24 = 30'd262144;
parameter    ap_ST_fsm_state25 = 30'd524288;
parameter    ap_ST_fsm_pp3_stage0 = 30'd1048576;
parameter    ap_ST_fsm_state29 = 30'd2097152;
parameter    ap_ST_fsm_pp4_stage0 = 30'd4194304;
parameter    ap_ST_fsm_state32 = 30'd8388608;
parameter    ap_ST_fsm_pp5_stage0 = 30'd16777216;
parameter    ap_ST_fsm_state36 = 30'd33554432;
parameter    ap_ST_fsm_state37 = 30'd67108864;
parameter    ap_ST_fsm_state38 = 30'd134217728;
parameter    ap_ST_fsm_state39 = 30'd268435456;
parameter    ap_ST_fsm_state40 = 30'd536870912;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_M00_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_M00_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_M00_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_M00_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_M00_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_M00_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_M00_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_M00_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_M00_AXI_USER_VALUE = 0;
parameter    C_M_AXI_M00_AXI_PROT_VALUE = 0;
parameter    C_M_AXI_M00_AXI_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_M01_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_M01_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_M01_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_M01_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_M01_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_M01_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_M01_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_M01_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_M01_AXI_USER_VALUE = 0;
parameter    C_M_AXI_M01_AXI_PROT_VALUE = 0;
parameter    C_M_AXI_M01_AXI_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_M00_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_M01_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_m00_axi_AWVALID;
input   m_axi_m00_axi_AWREADY;
output  [C_M_AXI_M00_AXI_ADDR_WIDTH - 1:0] m_axi_m00_axi_AWADDR;
output  [C_M_AXI_M00_AXI_ID_WIDTH - 1:0] m_axi_m00_axi_AWID;
output  [7:0] m_axi_m00_axi_AWLEN;
output  [2:0] m_axi_m00_axi_AWSIZE;
output  [1:0] m_axi_m00_axi_AWBURST;
output  [1:0] m_axi_m00_axi_AWLOCK;
output  [3:0] m_axi_m00_axi_AWCACHE;
output  [2:0] m_axi_m00_axi_AWPROT;
output  [3:0] m_axi_m00_axi_AWQOS;
output  [3:0] m_axi_m00_axi_AWREGION;
output  [C_M_AXI_M00_AXI_AWUSER_WIDTH - 1:0] m_axi_m00_axi_AWUSER;
output   m_axi_m00_axi_WVALID;
input   m_axi_m00_axi_WREADY;
output  [C_M_AXI_M00_AXI_DATA_WIDTH - 1:0] m_axi_m00_axi_WDATA;
output  [C_M_AXI_M00_AXI_WSTRB_WIDTH - 1:0] m_axi_m00_axi_WSTRB;
output   m_axi_m00_axi_WLAST;
output  [C_M_AXI_M00_AXI_ID_WIDTH - 1:0] m_axi_m00_axi_WID;
output  [C_M_AXI_M00_AXI_WUSER_WIDTH - 1:0] m_axi_m00_axi_WUSER;
output   m_axi_m00_axi_ARVALID;
input   m_axi_m00_axi_ARREADY;
output  [C_M_AXI_M00_AXI_ADDR_WIDTH - 1:0] m_axi_m00_axi_ARADDR;
output  [C_M_AXI_M00_AXI_ID_WIDTH - 1:0] m_axi_m00_axi_ARID;
output  [7:0] m_axi_m00_axi_ARLEN;
output  [2:0] m_axi_m00_axi_ARSIZE;
output  [1:0] m_axi_m00_axi_ARBURST;
output  [1:0] m_axi_m00_axi_ARLOCK;
output  [3:0] m_axi_m00_axi_ARCACHE;
output  [2:0] m_axi_m00_axi_ARPROT;
output  [3:0] m_axi_m00_axi_ARQOS;
output  [3:0] m_axi_m00_axi_ARREGION;
output  [C_M_AXI_M00_AXI_ARUSER_WIDTH - 1:0] m_axi_m00_axi_ARUSER;
input   m_axi_m00_axi_RVALID;
output   m_axi_m00_axi_RREADY;
input  [C_M_AXI_M00_AXI_DATA_WIDTH - 1:0] m_axi_m00_axi_RDATA;
input   m_axi_m00_axi_RLAST;
input  [C_M_AXI_M00_AXI_ID_WIDTH - 1:0] m_axi_m00_axi_RID;
input  [C_M_AXI_M00_AXI_RUSER_WIDTH - 1:0] m_axi_m00_axi_RUSER;
input  [1:0] m_axi_m00_axi_RRESP;
input   m_axi_m00_axi_BVALID;
output   m_axi_m00_axi_BREADY;
input  [1:0] m_axi_m00_axi_BRESP;
input  [C_M_AXI_M00_AXI_ID_WIDTH - 1:0] m_axi_m00_axi_BID;
input  [C_M_AXI_M00_AXI_BUSER_WIDTH - 1:0] m_axi_m00_axi_BUSER;
output   m_axi_m01_axi_AWVALID;
input   m_axi_m01_axi_AWREADY;
output  [C_M_AXI_M01_AXI_ADDR_WIDTH - 1:0] m_axi_m01_axi_AWADDR;
output  [C_M_AXI_M01_AXI_ID_WIDTH - 1:0] m_axi_m01_axi_AWID;
output  [7:0] m_axi_m01_axi_AWLEN;
output  [2:0] m_axi_m01_axi_AWSIZE;
output  [1:0] m_axi_m01_axi_AWBURST;
output  [1:0] m_axi_m01_axi_AWLOCK;
output  [3:0] m_axi_m01_axi_AWCACHE;
output  [2:0] m_axi_m01_axi_AWPROT;
output  [3:0] m_axi_m01_axi_AWQOS;
output  [3:0] m_axi_m01_axi_AWREGION;
output  [C_M_AXI_M01_AXI_AWUSER_WIDTH - 1:0] m_axi_m01_axi_AWUSER;
output   m_axi_m01_axi_WVALID;
input   m_axi_m01_axi_WREADY;
output  [C_M_AXI_M01_AXI_DATA_WIDTH - 1:0] m_axi_m01_axi_WDATA;
output  [C_M_AXI_M01_AXI_WSTRB_WIDTH - 1:0] m_axi_m01_axi_WSTRB;
output   m_axi_m01_axi_WLAST;
output  [C_M_AXI_M01_AXI_ID_WIDTH - 1:0] m_axi_m01_axi_WID;
output  [C_M_AXI_M01_AXI_WUSER_WIDTH - 1:0] m_axi_m01_axi_WUSER;
output   m_axi_m01_axi_ARVALID;
input   m_axi_m01_axi_ARREADY;
output  [C_M_AXI_M01_AXI_ADDR_WIDTH - 1:0] m_axi_m01_axi_ARADDR;
output  [C_M_AXI_M01_AXI_ID_WIDTH - 1:0] m_axi_m01_axi_ARID;
output  [7:0] m_axi_m01_axi_ARLEN;
output  [2:0] m_axi_m01_axi_ARSIZE;
output  [1:0] m_axi_m01_axi_ARBURST;
output  [1:0] m_axi_m01_axi_ARLOCK;
output  [3:0] m_axi_m01_axi_ARCACHE;
output  [2:0] m_axi_m01_axi_ARPROT;
output  [3:0] m_axi_m01_axi_ARQOS;
output  [3:0] m_axi_m01_axi_ARREGION;
output  [C_M_AXI_M01_AXI_ARUSER_WIDTH - 1:0] m_axi_m01_axi_ARUSER;
input   m_axi_m01_axi_RVALID;
output   m_axi_m01_axi_RREADY;
input  [C_M_AXI_M01_AXI_DATA_WIDTH - 1:0] m_axi_m01_axi_RDATA;
input   m_axi_m01_axi_RLAST;
input  [C_M_AXI_M01_AXI_ID_WIDTH - 1:0] m_axi_m01_axi_RID;
input  [C_M_AXI_M01_AXI_RUSER_WIDTH - 1:0] m_axi_m01_axi_RUSER;
input  [1:0] m_axi_m01_axi_RRESP;
input   m_axi_m01_axi_BVALID;
output   m_axi_m01_axi_BREADY;
input  [1:0] m_axi_m01_axi_BRESP;
input  [C_M_AXI_M01_AXI_ID_WIDTH - 1:0] m_axi_m01_axi_BID;
input  [C_M_AXI_M01_AXI_BUSER_WIDTH - 1:0] m_axi_m01_axi_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [29:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] scalar00;
wire   [63:0] A;
wire   [63:0] B;
reg    m00_axi_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    m00_axi_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln52_reg_496;
reg    m00_axi_blk_n_AW;
wire    ap_CS_fsm_state15;
reg    m00_axi_blk_n_B;
wire    ap_CS_fsm_state24;
reg    m00_axi_blk_n_W;
reg    ap_enable_reg_pp2_iter2;
wire    ap_block_pp2_stage0;
reg   [0:0] icmp_ln60_reg_529;
reg   [0:0] icmp_ln60_reg_529_pp2_iter1_reg;
reg    m01_axi_blk_n_AR;
wire    ap_CS_fsm_state19;
reg    m01_axi_blk_n_R;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter1;
wire    ap_block_pp3_stage0;
reg   [0:0] icmp_ln73_reg_548;
reg    m01_axi_blk_n_AW;
wire    ap_CS_fsm_state32;
reg    m01_axi_blk_n_W;
reg    ap_enable_reg_pp5_iter2;
wire    ap_block_pp5_stage0;
reg   [0:0] icmp_ln81_reg_581;
reg   [0:0] icmp_ln81_reg_581_pp5_iter1_reg;
reg    m01_axi_blk_n_B;
wire    ap_CS_fsm_state40;
reg    m00_axi_AWVALID;
wire    m00_axi_AWREADY;
reg    m00_axi_WVALID;
wire    m00_axi_WREADY;
reg    m00_axi_ARVALID;
wire    m00_axi_ARREADY;
wire    m00_axi_RVALID;
reg    m00_axi_RREADY;
wire   [31:0] m00_axi_RDATA;
wire    m00_axi_RLAST;
wire   [0:0] m00_axi_RID;
wire   [0:0] m00_axi_RUSER;
wire   [1:0] m00_axi_RRESP;
wire    m00_axi_BVALID;
reg    m00_axi_BREADY;
wire   [1:0] m00_axi_BRESP;
wire   [0:0] m00_axi_BID;
wire   [0:0] m00_axi_BUSER;
reg    m01_axi_AWVALID;
wire    m01_axi_AWREADY;
reg    m01_axi_WVALID;
wire    m01_axi_WREADY;
reg    m01_axi_ARVALID;
wire    m01_axi_ARREADY;
wire    m01_axi_RVALID;
reg    m01_axi_RREADY;
wire   [31:0] m01_axi_RDATA;
wire    m01_axi_RLAST;
wire   [0:0] m01_axi_RID;
wire   [0:0] m01_axi_RUSER;
wire   [1:0] m01_axi_RRESP;
wire    m01_axi_BVALID;
reg    m01_axi_BREADY;
wire   [1:0] m01_axi_BRESP;
wire   [0:0] m01_axi_BID;
wire   [0:0] m01_axi_BUSER;
reg   [12:0] phi_ln52_reg_258;
reg   [12:0] phi_ln52_reg_258_pp0_iter1_reg;
wire    ap_block_state9_pp0_stage0_iter0;
reg    ap_block_state10_pp0_stage0_iter1;
wire    ap_block_state11_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [12:0] i_0_reg_270;
reg   [12:0] phi_ln60_reg_281;
reg   [12:0] phi_ln73_reg_292;
reg   [12:0] phi_ln73_reg_292_pp3_iter1_reg;
wire    ap_block_state26_pp3_stage0_iter0;
reg    ap_block_state27_pp3_stage0_iter1;
wire    ap_block_state28_pp3_stage0_iter2;
reg    ap_block_pp3_stage0_11001;
reg   [12:0] i1_0_reg_304;
reg   [12:0] phi_ln81_reg_315;
reg   [63:0] m01_axi_addr_reg_482;
reg   [63:0] m00_axi_addr_reg_489;
wire   [0:0] icmp_ln52_fu_366_p2;
reg   [0:0] icmp_ln52_reg_496_pp0_iter1_reg;
wire   [12:0] add_ln52_fu_372_p2;
reg   [12:0] add_ln52_reg_500;
reg    ap_enable_reg_pp0_iter0;
reg   [31:0] m00_axi_addr_read_reg_505;
wire   [0:0] icmp_ln55_fu_383_p2;
reg   [0:0] icmp_ln55_reg_510;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state13_pp1_stage0_iter0;
wire    ap_block_state14_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [12:0] i_fu_389_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [63:0] zext_ln56_fu_395_p1;
reg   [63:0] zext_ln56_reg_519;
wire   [0:0] icmp_ln60_fu_407_p2;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state16_pp2_stage0_iter0;
wire    ap_block_state17_pp2_stage0_iter1;
wire    ap_block_state18_pp2_stage0_iter2;
reg    ap_block_state18_io;
reg    ap_block_pp2_stage0_11001;
wire   [12:0] add_ln60_fu_413_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [31:0] m00_axi_output_buffer_q0;
reg   [31:0] m00_axi_output_buffer_load_reg_543;
reg    ap_enable_reg_pp2_iter1;
wire   [0:0] icmp_ln73_fu_424_p2;
reg   [0:0] icmp_ln73_reg_548_pp3_iter1_reg;
wire   [12:0] add_ln73_fu_430_p2;
reg   [12:0] add_ln73_reg_552;
reg    ap_enable_reg_pp3_iter0;
reg   [31:0] m01_axi_addr_read_reg_557;
wire   [0:0] icmp_ln76_fu_441_p2;
reg   [0:0] icmp_ln76_reg_562;
wire    ap_CS_fsm_pp4_stage0;
wire    ap_block_state30_pp4_stage0_iter0;
wire    ap_block_state31_pp4_stage0_iter1;
wire    ap_block_pp4_stage0_11001;
wire   [12:0] i_1_fu_447_p2;
reg    ap_enable_reg_pp4_iter0;
wire   [63:0] zext_ln77_fu_453_p1;
reg   [63:0] zext_ln77_reg_571;
wire   [0:0] icmp_ln81_fu_465_p2;
wire    ap_CS_fsm_pp5_stage0;
wire    ap_block_state33_pp5_stage0_iter0;
wire    ap_block_state34_pp5_stage0_iter1;
wire    ap_block_state35_pp5_stage0_iter2;
reg    ap_block_state35_io;
reg    ap_block_pp5_stage0_11001;
wire   [12:0] add_ln81_fu_471_p2;
reg    ap_enable_reg_pp5_iter0;
wire   [31:0] m01_axi_output_buffer_q0;
reg   [31:0] m01_axi_output_buffer_load_reg_595;
reg    ap_enable_reg_pp5_iter1;
wire    ap_CS_fsm_state8;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state9;
reg    ap_enable_reg_pp0_iter2;
wire    ap_CS_fsm_state12;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state13;
reg    ap_enable_reg_pp1_iter1;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state16;
wire    ap_CS_fsm_state25;
reg    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state26;
reg    ap_enable_reg_pp3_iter2;
wire    ap_CS_fsm_state29;
wire    ap_block_pp4_stage0_subdone;
reg    ap_condition_pp4_exit_iter0_state30;
reg    ap_enable_reg_pp4_iter1;
reg    ap_block_pp5_stage0_subdone;
reg    ap_condition_pp5_exit_iter0_state33;
reg   [12:0] m00_axi_input_buffer_address0;
reg    m00_axi_input_buffer_ce0;
reg    m00_axi_input_buffer_we0;
wire   [31:0] m00_axi_input_buffer_q0;
reg   [12:0] m00_axi_output_buffer_address0;
reg    m00_axi_output_buffer_ce0;
reg    m00_axi_output_buffer_we0;
wire   [31:0] m00_axi_output_buffer_d0;
reg   [12:0] m01_axi_input_buffer_address0;
reg    m01_axi_input_buffer_ce0;
reg    m01_axi_input_buffer_we0;
wire   [31:0] m01_axi_input_buffer_q0;
reg   [12:0] m01_axi_output_buffer_address0;
reg    m01_axi_output_buffer_ce0;
reg    m01_axi_output_buffer_we0;
wire   [31:0] m01_axi_output_buffer_d0;
reg   [12:0] ap_phi_mux_phi_ln52_phi_fu_262_p4;
reg   [12:0] ap_phi_mux_phi_ln73_phi_fu_296_p4;
wire   [63:0] zext_ln52_fu_378_p1;
wire    ap_block_pp1_stage0;
wire   [63:0] zext_ln60_fu_419_p1;
wire   [63:0] zext_ln73_fu_436_p1;
wire    ap_block_pp4_stage0;
wire   [63:0] zext_ln81_fu_477_p1;
wire   [63:0] empty_fu_336_p1;
wire   [63:0] empty_6_fu_356_p1;
wire    ap_block_pp2_stage0_01001;
wire    ap_block_pp5_stage0_01001;
wire   [61:0] B3_fu_326_p4;
wire   [61:0] A1_fu_346_p4;
reg   [29:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_idle_pp4;
wire    ap_enable_pp4;
reg    ap_idle_pp5;
wire    ap_enable_pp5;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 30'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp5_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp4_iter0 = 1'b0;
#0 ap_enable_reg_pp5_iter0 = 1'b0;
#0 ap_enable_reg_pp5_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp4_iter1 = 1'b0;
end

Vadd_A_B_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
Vadd_A_B_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .scalar00(scalar00),
    .A(A),
    .B(B)
);

Vadd_A_B_m00_axi_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_M00_AXI_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_M00_AXI_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_M00_AXI_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_M00_AXI_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_M00_AXI_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_M00_AXI_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_M00_AXI_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_M00_AXI_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_M00_AXI_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_M00_AXI_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_M00_AXI_CACHE_VALUE ))
Vadd_A_B_m00_axi_m_axi_U(
    .AWVALID(m_axi_m00_axi_AWVALID),
    .AWREADY(m_axi_m00_axi_AWREADY),
    .AWADDR(m_axi_m00_axi_AWADDR),
    .AWID(m_axi_m00_axi_AWID),
    .AWLEN(m_axi_m00_axi_AWLEN),
    .AWSIZE(m_axi_m00_axi_AWSIZE),
    .AWBURST(m_axi_m00_axi_AWBURST),
    .AWLOCK(m_axi_m00_axi_AWLOCK),
    .AWCACHE(m_axi_m00_axi_AWCACHE),
    .AWPROT(m_axi_m00_axi_AWPROT),
    .AWQOS(m_axi_m00_axi_AWQOS),
    .AWREGION(m_axi_m00_axi_AWREGION),
    .AWUSER(m_axi_m00_axi_AWUSER),
    .WVALID(m_axi_m00_axi_WVALID),
    .WREADY(m_axi_m00_axi_WREADY),
    .WDATA(m_axi_m00_axi_WDATA),
    .WSTRB(m_axi_m00_axi_WSTRB),
    .WLAST(m_axi_m00_axi_WLAST),
    .WID(m_axi_m00_axi_WID),
    .WUSER(m_axi_m00_axi_WUSER),
    .ARVALID(m_axi_m00_axi_ARVALID),
    .ARREADY(m_axi_m00_axi_ARREADY),
    .ARADDR(m_axi_m00_axi_ARADDR),
    .ARID(m_axi_m00_axi_ARID),
    .ARLEN(m_axi_m00_axi_ARLEN),
    .ARSIZE(m_axi_m00_axi_ARSIZE),
    .ARBURST(m_axi_m00_axi_ARBURST),
    .ARLOCK(m_axi_m00_axi_ARLOCK),
    .ARCACHE(m_axi_m00_axi_ARCACHE),
    .ARPROT(m_axi_m00_axi_ARPROT),
    .ARQOS(m_axi_m00_axi_ARQOS),
    .ARREGION(m_axi_m00_axi_ARREGION),
    .ARUSER(m_axi_m00_axi_ARUSER),
    .RVALID(m_axi_m00_axi_RVALID),
    .RREADY(m_axi_m00_axi_RREADY),
    .RDATA(m_axi_m00_axi_RDATA),
    .RLAST(m_axi_m00_axi_RLAST),
    .RID(m_axi_m00_axi_RID),
    .RUSER(m_axi_m00_axi_RUSER),
    .RRESP(m_axi_m00_axi_RRESP),
    .BVALID(m_axi_m00_axi_BVALID),
    .BREADY(m_axi_m00_axi_BREADY),
    .BRESP(m_axi_m00_axi_BRESP),
    .BID(m_axi_m00_axi_BID),
    .BUSER(m_axi_m00_axi_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(m00_axi_ARVALID),
    .I_ARREADY(m00_axi_ARREADY),
    .I_ARADDR(m00_axi_addr_reg_489),
    .I_ARID(1'd0),
    .I_ARLEN(32'd4096),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(m00_axi_RVALID),
    .I_RREADY(m00_axi_RREADY),
    .I_RDATA(m00_axi_RDATA),
    .I_RID(m00_axi_RID),
    .I_RUSER(m00_axi_RUSER),
    .I_RRESP(m00_axi_RRESP),
    .I_RLAST(m00_axi_RLAST),
    .I_AWVALID(m00_axi_AWVALID),
    .I_AWREADY(m00_axi_AWREADY),
    .I_AWADDR(m00_axi_addr_reg_489),
    .I_AWID(1'd0),
    .I_AWLEN(32'd4096),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(m00_axi_WVALID),
    .I_WREADY(m00_axi_WREADY),
    .I_WDATA(m00_axi_output_buffer_load_reg_543),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(m00_axi_BVALID),
    .I_BREADY(m00_axi_BREADY),
    .I_BRESP(m00_axi_BRESP),
    .I_BID(m00_axi_BID),
    .I_BUSER(m00_axi_BUSER)
);

Vadd_A_B_m01_axi_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_M01_AXI_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_M01_AXI_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_M01_AXI_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_M01_AXI_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_M01_AXI_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_M01_AXI_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_M01_AXI_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_M01_AXI_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_M01_AXI_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_M01_AXI_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_M01_AXI_CACHE_VALUE ))
Vadd_A_B_m01_axi_m_axi_U(
    .AWVALID(m_axi_m01_axi_AWVALID),
    .AWREADY(m_axi_m01_axi_AWREADY),
    .AWADDR(m_axi_m01_axi_AWADDR),
    .AWID(m_axi_m01_axi_AWID),
    .AWLEN(m_axi_m01_axi_AWLEN),
    .AWSIZE(m_axi_m01_axi_AWSIZE),
    .AWBURST(m_axi_m01_axi_AWBURST),
    .AWLOCK(m_axi_m01_axi_AWLOCK),
    .AWCACHE(m_axi_m01_axi_AWCACHE),
    .AWPROT(m_axi_m01_axi_AWPROT),
    .AWQOS(m_axi_m01_axi_AWQOS),
    .AWREGION(m_axi_m01_axi_AWREGION),
    .AWUSER(m_axi_m01_axi_AWUSER),
    .WVALID(m_axi_m01_axi_WVALID),
    .WREADY(m_axi_m01_axi_WREADY),
    .WDATA(m_axi_m01_axi_WDATA),
    .WSTRB(m_axi_m01_axi_WSTRB),
    .WLAST(m_axi_m01_axi_WLAST),
    .WID(m_axi_m01_axi_WID),
    .WUSER(m_axi_m01_axi_WUSER),
    .ARVALID(m_axi_m01_axi_ARVALID),
    .ARREADY(m_axi_m01_axi_ARREADY),
    .ARADDR(m_axi_m01_axi_ARADDR),
    .ARID(m_axi_m01_axi_ARID),
    .ARLEN(m_axi_m01_axi_ARLEN),
    .ARSIZE(m_axi_m01_axi_ARSIZE),
    .ARBURST(m_axi_m01_axi_ARBURST),
    .ARLOCK(m_axi_m01_axi_ARLOCK),
    .ARCACHE(m_axi_m01_axi_ARCACHE),
    .ARPROT(m_axi_m01_axi_ARPROT),
    .ARQOS(m_axi_m01_axi_ARQOS),
    .ARREGION(m_axi_m01_axi_ARREGION),
    .ARUSER(m_axi_m01_axi_ARUSER),
    .RVALID(m_axi_m01_axi_RVALID),
    .RREADY(m_axi_m01_axi_RREADY),
    .RDATA(m_axi_m01_axi_RDATA),
    .RLAST(m_axi_m01_axi_RLAST),
    .RID(m_axi_m01_axi_RID),
    .RUSER(m_axi_m01_axi_RUSER),
    .RRESP(m_axi_m01_axi_RRESP),
    .BVALID(m_axi_m01_axi_BVALID),
    .BREADY(m_axi_m01_axi_BREADY),
    .BRESP(m_axi_m01_axi_BRESP),
    .BID(m_axi_m01_axi_BID),
    .BUSER(m_axi_m01_axi_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(m01_axi_ARVALID),
    .I_ARREADY(m01_axi_ARREADY),
    .I_ARADDR(m01_axi_addr_reg_482),
    .I_ARID(1'd0),
    .I_ARLEN(32'd4096),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(m01_axi_RVALID),
    .I_RREADY(m01_axi_RREADY),
    .I_RDATA(m01_axi_RDATA),
    .I_RID(m01_axi_RID),
    .I_RUSER(m01_axi_RUSER),
    .I_RRESP(m01_axi_RRESP),
    .I_RLAST(m01_axi_RLAST),
    .I_AWVALID(m01_axi_AWVALID),
    .I_AWREADY(m01_axi_AWREADY),
    .I_AWADDR(m01_axi_addr_reg_482),
    .I_AWID(1'd0),
    .I_AWLEN(32'd4096),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(m01_axi_WVALID),
    .I_WREADY(m01_axi_WREADY),
    .I_WDATA(m01_axi_output_buffer_load_reg_595),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(m01_axi_BVALID),
    .I_BREADY(m01_axi_BREADY),
    .I_BRESP(m01_axi_BRESP),
    .I_BID(m01_axi_BID),
    .I_BUSER(m01_axi_BUSER)
);

Vadd_A_B_m00_axi_input_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
m00_axi_input_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(m00_axi_input_buffer_address0),
    .ce0(m00_axi_input_buffer_ce0),
    .we0(m00_axi_input_buffer_we0),
    .d0(m00_axi_addr_read_reg_505),
    .q0(m00_axi_input_buffer_q0)
);

Vadd_A_B_m00_axi_input_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
m00_axi_output_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(m00_axi_output_buffer_address0),
    .ce0(m00_axi_output_buffer_ce0),
    .we0(m00_axi_output_buffer_we0),
    .d0(m00_axi_output_buffer_d0),
    .q0(m00_axi_output_buffer_q0)
);

Vadd_A_B_m00_axi_input_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
m01_axi_input_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(m01_axi_input_buffer_address0),
    .ce0(m01_axi_input_buffer_ce0),
    .we0(m01_axi_input_buffer_we0),
    .d0(m01_axi_addr_read_reg_557),
    .q0(m01_axi_input_buffer_q0)
);

Vadd_A_B_m00_axi_input_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
m01_axi_output_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(m01_axi_output_buffer_address0),
    .ce0(m01_axi_output_buffer_ce0),
    .we0(m01_axi_output_buffer_we0),
    .d0(m01_axi_output_buffer_d0),
    .q0(m01_axi_output_buffer_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state9) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state9)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state9);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state13) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state13))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state13);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state16) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((m00_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state16)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state16);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end else if (((m00_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
            ap_enable_reg_pp2_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_condition_pp3_exit_iter0_state26) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state25)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp3_exit_iter0_state26)) begin
                ap_enable_reg_pp3_iter1 <= (1'b1 ^ ap_condition_pp3_exit_iter0_state26);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end else if ((1'b1 == ap_CS_fsm_state25)) begin
            ap_enable_reg_pp3_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp4_stage0_subdone) & (1'b1 == ap_condition_pp4_exit_iter0_state30) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
            ap_enable_reg_pp4_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state29)) begin
            ap_enable_reg_pp4_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp4_stage0_subdone) & (1'b1 == ap_condition_pp4_exit_iter0_state30))) begin
            ap_enable_reg_pp4_iter1 <= (1'b1 ^ ap_condition_pp4_exit_iter0_state30);
        end else if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
        end else if ((1'b1 == ap_CS_fsm_state29)) begin
            ap_enable_reg_pp4_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp5_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp5_stage0_subdone) & (1'b1 == ap_condition_pp5_exit_iter0_state33) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
            ap_enable_reg_pp5_iter0 <= 1'b0;
        end else if (((m01_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
            ap_enable_reg_pp5_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp5_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp5_exit_iter0_state33)) begin
                ap_enable_reg_pp5_iter1 <= (1'b1 ^ ap_condition_pp5_exit_iter0_state33);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp5_iter1 <= ap_enable_reg_pp5_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp5_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter2 <= ap_enable_reg_pp5_iter1;
        end else if (((m01_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
            ap_enable_reg_pp5_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        i1_0_reg_304 <= 13'd0;
    end else if (((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (icmp_ln76_fu_441_p2 == 1'd0))) begin
        i1_0_reg_304 <= i_1_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_0_reg_270 <= 13'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln55_fu_383_p2 == 1'd0))) begin
        i_0_reg_270 <= i_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln52_reg_496 == 1'd0))) begin
        phi_ln52_reg_258 <= add_ln52_reg_500;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        phi_ln52_reg_258 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((m00_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        phi_ln60_reg_281 <= 13'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln60_fu_407_p2 == 1'd0))) begin
        phi_ln60_reg_281 <= add_ln60_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        phi_ln73_reg_292 <= 13'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (icmp_ln73_reg_548 == 1'd0))) begin
        phi_ln73_reg_292 <= add_ln73_reg_552;
    end
end

always @ (posedge ap_clk) begin
    if (((m01_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
        phi_ln81_reg_315 <= 13'd0;
    end else if (((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (icmp_ln81_fu_465_p2 == 1'd0))) begin
        phi_ln81_reg_315 <= add_ln81_fu_471_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln52_reg_500 <= add_ln52_fu_372_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        add_ln73_reg_552 <= add_ln73_fu_430_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln52_reg_496 <= icmp_ln52_fu_366_p2;
        icmp_ln52_reg_496_pp0_iter1_reg <= icmp_ln52_reg_496;
        phi_ln52_reg_258_pp0_iter1_reg <= phi_ln52_reg_258;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln55_reg_510 <= icmp_ln55_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln60_reg_529 <= icmp_ln60_fu_407_p2;
        icmp_ln60_reg_529_pp2_iter1_reg <= icmp_ln60_reg_529;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        icmp_ln73_reg_548 <= icmp_ln73_fu_424_p2;
        icmp_ln73_reg_548_pp3_iter1_reg <= icmp_ln73_reg_548;
        phi_ln73_reg_292_pp3_iter1_reg <= phi_ln73_reg_292;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        icmp_ln76_reg_562 <= icmp_ln76_fu_441_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp5_stage0_11001) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        icmp_ln81_reg_581 <= icmp_ln81_fu_465_p2;
        icmp_ln81_reg_581_pp5_iter1_reg <= icmp_ln81_reg_581;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln52_reg_496 == 1'd0))) begin
        m00_axi_addr_read_reg_505 <= m00_axi_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        m00_axi_addr_reg_489[61 : 0] <= empty_6_fu_356_p1[61 : 0];
        m01_axi_addr_reg_482[61 : 0] <= empty_fu_336_p1[61 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln60_reg_529 == 1'd0))) begin
        m00_axi_output_buffer_load_reg_543 <= m00_axi_output_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (icmp_ln73_reg_548 == 1'd0))) begin
        m01_axi_addr_read_reg_557 <= m01_axi_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (icmp_ln81_reg_581 == 1'd0))) begin
        m01_axi_output_buffer_load_reg_595 <= m01_axi_output_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln55_fu_383_p2 == 1'd0))) begin
        zext_ln56_reg_519[12 : 0] <= zext_ln56_fu_395_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0) & (icmp_ln76_fu_441_p2 == 1'd0))) begin
        zext_ln77_reg_571[12 : 0] <= zext_ln77_fu_453_p1[12 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln52_fu_366_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state9 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state9 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln55_fu_383_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state13 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state13 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln60_fu_407_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state16 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state16 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln73_fu_424_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state26 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state26 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln76_fu_441_p2 == 1'd1)) begin
        ap_condition_pp4_exit_iter0_state30 = 1'b1;
    end else begin
        ap_condition_pp4_exit_iter0_state30 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln81_fu_465_p2 == 1'd1)) begin
        ap_condition_pp5_exit_iter0_state33 = 1'b1;
    end else begin
        ap_condition_pp5_exit_iter0_state33 = 1'b0;
    end
end

always @ (*) begin
    if (((m01_axi_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b0) & (ap_enable_reg_pp4_iter0 == 1'b0))) begin
        ap_idle_pp4 = 1'b1;
    end else begin
        ap_idle_pp4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter1 == 1'b0) & (ap_enable_reg_pp5_iter0 == 1'b0) & (ap_enable_reg_pp5_iter2 == 1'b0))) begin
        ap_idle_pp5 = 1'b1;
    end else begin
        ap_idle_pp5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln52_reg_496 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_phi_ln52_phi_fu_262_p4 = add_ln52_reg_500;
    end else begin
        ap_phi_mux_phi_ln52_phi_fu_262_p4 = phi_ln52_reg_258;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (icmp_ln73_reg_548 == 1'd0))) begin
        ap_phi_mux_phi_ln73_phi_fu_296_p4 = add_ln73_reg_552;
    end else begin
        ap_phi_mux_phi_ln73_phi_fu_296_p4 = phi_ln73_reg_292;
    end
end

always @ (*) begin
    if (((m01_axi_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((m00_axi_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m00_axi_ARVALID = 1'b1;
    end else begin
        m00_axi_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m00_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        m00_axi_AWVALID = 1'b1;
    end else begin
        m00_axi_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m00_axi_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        m00_axi_BREADY = 1'b1;
    end else begin
        m00_axi_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln52_reg_496 == 1'd0))) begin
        m00_axi_RREADY = 1'b1;
    end else begin
        m00_axi_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter2 == 1'b1) & (icmp_ln60_reg_529_pp2_iter1_reg == 1'd0))) begin
        m00_axi_WVALID = 1'b1;
    end else begin
        m00_axi_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        m00_axi_blk_n_AR = m_axi_m00_axi_ARREADY;
    end else begin
        m00_axi_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        m00_axi_blk_n_AW = m_axi_m00_axi_AWREADY;
    end else begin
        m00_axi_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        m00_axi_blk_n_B = m_axi_m00_axi_BVALID;
    end else begin
        m00_axi_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln52_reg_496 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        m00_axi_blk_n_R = m_axi_m00_axi_RVALID;
    end else begin
        m00_axi_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (icmp_ln60_reg_529_pp2_iter1_reg == 1'd0))) begin
        m00_axi_blk_n_W = m_axi_m00_axi_WREADY;
    end else begin
        m00_axi_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        m00_axi_input_buffer_address0 = zext_ln56_fu_395_p1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        m00_axi_input_buffer_address0 = zext_ln52_fu_378_p1;
    end else begin
        m00_axi_input_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        m00_axi_input_buffer_ce0 = 1'b1;
    end else begin
        m00_axi_input_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln52_reg_496_pp0_iter1_reg == 1'd0))) begin
        m00_axi_input_buffer_we0 = 1'b1;
    end else begin
        m00_axi_input_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        m00_axi_output_buffer_address0 = zext_ln60_fu_419_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        m00_axi_output_buffer_address0 = zext_ln56_reg_519;
    end else begin
        m00_axi_output_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        m00_axi_output_buffer_ce0 = 1'b1;
    end else begin
        m00_axi_output_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln55_reg_510 == 1'd0))) begin
        m00_axi_output_buffer_we0 = 1'b1;
    end else begin
        m00_axi_output_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((m01_axi_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        m01_axi_ARVALID = 1'b1;
    end else begin
        m01_axi_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m01_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
        m01_axi_AWVALID = 1'b1;
    end else begin
        m01_axi_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m01_axi_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
        m01_axi_BREADY = 1'b1;
    end else begin
        m01_axi_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (icmp_ln73_reg_548 == 1'd0))) begin
        m01_axi_RREADY = 1'b1;
    end else begin
        m01_axi_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter2 == 1'b1) & (icmp_ln81_reg_581_pp5_iter1_reg == 1'd0))) begin
        m01_axi_WVALID = 1'b1;
    end else begin
        m01_axi_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        m01_axi_blk_n_AR = m_axi_m01_axi_ARREADY;
    end else begin
        m01_axi_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        m01_axi_blk_n_AW = m_axi_m01_axi_AWREADY;
    end else begin
        m01_axi_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        m01_axi_blk_n_B = m_axi_m01_axi_BVALID;
    end else begin
        m01_axi_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (icmp_ln73_reg_548 == 1'd0))) begin
        m01_axi_blk_n_R = m_axi_m01_axi_RVALID;
    end else begin
        m01_axi_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp5_stage0) & (ap_enable_reg_pp5_iter2 == 1'b1) & (icmp_ln81_reg_581_pp5_iter1_reg == 1'd0))) begin
        m01_axi_blk_n_W = m_axi_m01_axi_WREADY;
    end else begin
        m01_axi_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        m01_axi_input_buffer_address0 = zext_ln77_fu_453_p1;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        m01_axi_input_buffer_address0 = zext_ln73_fu_436_p1;
    end else begin
        m01_axi_input_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0)) | ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1)))) begin
        m01_axi_input_buffer_ce0 = 1'b1;
    end else begin
        m01_axi_input_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln73_reg_548_pp3_iter1_reg == 1'd0))) begin
        m01_axi_input_buffer_we0 = 1'b1;
    end else begin
        m01_axi_input_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp5_stage0) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        m01_axi_output_buffer_address0 = zext_ln81_fu_477_p1;
    end else if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        m01_axi_output_buffer_address0 = zext_ln77_reg_571;
    end else begin
        m01_axi_output_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0)) | ((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0)))) begin
        m01_axi_output_buffer_ce0 = 1'b1;
    end else begin
        m01_axi_output_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (icmp_ln76_reg_562 == 1'd0))) begin
        m01_axi_output_buffer_we0 = 1'b1;
    end else begin
        m01_axi_output_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m00_axi_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln52_fu_366_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln52_fu_366_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln55_fu_383_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln55_fu_383_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((m00_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (icmp_ln60_fu_407_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (icmp_ln60_fu_407_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)) | ((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((m01_axi_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((m00_axi_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((1'b0 == ap_block_pp3_stage0_subdone) & (icmp_ln73_fu_424_p2 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if ((((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b1)) | ((1'b0 == ap_block_pp3_stage0_subdone) & (icmp_ln73_fu_424_p2 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_pp4_stage0;
        end
        ap_ST_fsm_pp4_stage0 : begin
            if (~((1'b0 == ap_block_pp4_stage0_subdone) & (icmp_ln76_fu_441_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else if (((1'b0 == ap_block_pp4_stage0_subdone) & (icmp_ln76_fu_441_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end
        end
        ap_ST_fsm_state32 : begin
            if (((m01_axi_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_pp5_stage0 : begin
            if ((~((1'b0 == ap_block_pp5_stage0_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0) & (icmp_ln81_fu_465_p2 == 1'd1) & (ap_enable_reg_pp5_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp5_stage0_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0) & (ap_enable_reg_pp5_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end else if ((((1'b0 == ap_block_pp5_stage0_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0) & (icmp_ln81_fu_465_p2 == 1'd1) & (ap_enable_reg_pp5_iter0 == 1'b1)) | ((1'b0 == ap_block_pp5_stage0_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0) & (ap_enable_reg_pp5_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            if (((m01_axi_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A1_fu_346_p4 = {{A[63:2]}};

assign B3_fu_326_p4 = {{B[63:2]}};

assign add_ln52_fu_372_p2 = (ap_phi_mux_phi_ln52_phi_fu_262_p4 + 13'd1);

assign add_ln60_fu_413_p2 = (phi_ln60_reg_281 + 13'd1);

assign add_ln73_fu_430_p2 = (ap_phi_mux_phi_ln73_phi_fu_296_p4 + 13'd1);

assign add_ln81_fu_471_p2 = (phi_ln81_reg_315 + 13'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_pp4_stage0 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_pp5_stage0 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m00_axi_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln52_reg_496 == 1'd0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m00_axi_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln52_reg_496 == 1'd0));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((1'b1 == ap_block_state18_io) & (ap_enable_reg_pp2_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((1'b1 == ap_block_state18_io) & (ap_enable_reg_pp2_iter2 == 1'b1));
end

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_11001 = ((m01_axi_RVALID == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln73_reg_548 == 1'd0));
end

always @ (*) begin
    ap_block_pp3_stage0_subdone = ((m01_axi_RVALID == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln73_reg_548 == 1'd0));
end

assign ap_block_pp4_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp5_stage0_11001 = ((1'b1 == ap_block_state35_io) & (ap_enable_reg_pp5_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp5_stage0_subdone = ((1'b1 == ap_block_state35_io) & (ap_enable_reg_pp5_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter1 = ((m00_axi_RVALID == 1'b0) & (icmp_ln52_reg_496 == 1'd0));
end

assign ap_block_state11_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state18_io = ((m00_axi_WREADY == 1'b0) & (icmp_ln60_reg_529_pp2_iter1_reg == 1'd0));
end

assign ap_block_state18_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state27_pp3_stage0_iter1 = ((m01_axi_RVALID == 1'b0) & (icmp_ln73_reg_548 == 1'd0));
end

assign ap_block_state28_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp4_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp4_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp5_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp5_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state35_io = ((m01_axi_WREADY == 1'b0) & (icmp_ln81_reg_581_pp5_iter1_reg == 1'd0));
end

assign ap_block_state35_pp5_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_enable_pp4 = (ap_idle_pp4 ^ 1'b1);

assign ap_enable_pp5 = (ap_idle_pp5 ^ 1'b1);

assign empty_6_fu_356_p1 = A1_fu_346_p4;

assign empty_fu_336_p1 = B3_fu_326_p4;

assign i_1_fu_447_p2 = (i1_0_reg_304 + 13'd1);

assign i_fu_389_p2 = (i_0_reg_270 + 13'd1);

assign icmp_ln52_fu_366_p2 = ((ap_phi_mux_phi_ln52_phi_fu_262_p4 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_383_p2 = ((i_0_reg_270 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_407_p2 = ((phi_ln60_reg_281 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_424_p2 = ((ap_phi_mux_phi_ln73_phi_fu_296_p4 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_441_p2 = ((i1_0_reg_304 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_465_p2 = ((phi_ln81_reg_315 == 13'd4096) ? 1'b1 : 1'b0);

assign m00_axi_output_buffer_d0 = (m00_axi_input_buffer_q0 + 32'd1);

assign m01_axi_output_buffer_d0 = (m01_axi_input_buffer_q0 + 32'd1);

assign zext_ln52_fu_378_p1 = phi_ln52_reg_258_pp0_iter1_reg;

assign zext_ln56_fu_395_p1 = i_0_reg_270;

assign zext_ln60_fu_419_p1 = phi_ln60_reg_281;

assign zext_ln73_fu_436_p1 = phi_ln73_reg_292_pp3_iter1_reg;

assign zext_ln77_fu_453_p1 = i1_0_reg_304;

assign zext_ln81_fu_477_p1 = phi_ln81_reg_315;

always @ (posedge ap_clk) begin
    m01_axi_addr_reg_482[63:62] <= 2'b00;
    m00_axi_addr_reg_489[63:62] <= 2'b00;
    zext_ln56_reg_519[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
    zext_ln77_reg_571[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //Vadd_A_B
